
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const APP_KEY='vfy_nsw_state_v3'; const APP_VERSION='1.3.1'; let state, page='dashboard', selectedMachine=null, machineTab='details', runDate=today();
function today(){return new Date().toISOString().slice(0,10)} function uid(p='id'){return p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(APP_KEY,JSON.stringify(state));}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
const SAFETY_LOCKERS={
  '59':[
    {id:'hardhat',name:'Hardhat',price:25,sold:79,productId:'59-61'},
    {id:'glove-clip',name:'Glove & clip',price:25,sold:14,productId:'59-63'},
    {id:'vest',name:'Vest',price:15,sold:47,productId:'59-62'},
    {id:'earmuffs',name:'Earmuffs',price:20,sold:0,productId:'59-64'},
    {id:'dust-mask',name:'Dust Mask',price:20,sold:9,productId:'59-65'},
    {id:'safety-glasses',name:'Safety glasses',price:20,sold:3,productId:'59-66'},
    {id:'latch',name:'Latch',price:6,sold:0,productId:'59-67'}
  ],
  '60':[
    {id:'hardhat',name:'Hardhat',price:20,sold:58,productId:'60-56'},
    {id:'vest',name:'Vest',price:15,sold:23,productId:'60-57'},
    {id:'earmuffs',name:'Earmuffs',price:20,sold:0,productId:'60-61'},
    {id:'dust-mask',name:'Dust Mask',price:20,sold:3,productId:'60-59'},
    {id:'safety-glasses',name:'Safety glasses',price:20,sold:4,productId:'60-60'},
    {id:'glove-clip',name:'Glove & clip',price:25,sold:18,productId:'60-58'}
  ],
  '61':[
    {id:'hardhat',name:'Hardhat',price:20,sold:0,productId:'61-56'},
    {id:'vest',name:'Vest',price:15,sold:0,productId:'61-57'},
    {id:'earmuffs',name:'Earmuffs',price:20,sold:0,productId:'61-61'},
    {id:'dust-mask',name:'Dust Mask',price:20,sold:0,productId:'61-59'},
    {id:'safety-glasses',name:'Safety glasses',price:20,sold:0,productId:'61-60'},
    {id:'glove-clip',name:'Glove & clip',price:25,sold:1,productId:'61-58'}
  ],
  '63':[
    {id:'hardhat',name:'Hardhat',price:25,sold:44,productId:'63-57'},
    {id:'vest',name:'Vest',price:15,sold:9,productId:'63-58'},
    {id:'earmuffs',name:'Earmuffs',price:20,sold:0,productId:'63-62'},
    {id:'dust-mask',name:'Dust Mask',price:20,sold:1,productId:'63-60'},
    {id:'safety-glasses',name:'Safety glasses',price:20,sold:0,productId:'63-61'},
    {id:'glove-clip',name:'Glove & clip',price:25,sold:10,productId:'63-59'}
  ],
  '64':[
    {id:'hardhat',name:'Hardhat',price:25,sold:67,productId:'64-89'},
    {id:'glove-clip',name:'Glove & clip',price:25,sold:11,productId:'64-91'},
    {id:'vest',name:'Vest',price:15,sold:28,productId:'64-90'},
    {id:'earmuffs',name:'Earmuffs',price:20,sold:0,productId:'64-92'},
    {id:'dust-mask',name:'Dust Mask',price:20,sold:7,productId:'64-93'},
    {id:'safety-glasses',name:'Safety glasses',price:20,sold:6,productId:'64-94'},
    {id:'latch',name:'Latch',price:6,sold:0,productId:'64-95'}
  ]
};
const SAFETY_LOCKER_PHOTOS={
  '59':'safety-locker-59.jpg',
  '63':'safety-locker-63.jpg',
  '64':'safety-locker-64.jpg'
};
async function init(){let local=localStorage.getItem(APP_KEY); if(local) state=JSON.parse(local); else {state=await fetch('data.json').then(r=>r.json());state.updatedAt=new Date().toISOString()} migrateState(); cleanup(); registerSW(); render();}
function migrateState(){
  state.migrations=state.migrations||{};
  // Re-apply with a new migration key so devices that already saved older local data are fixed too.
  if(!state.migrations.holdmark37CategoriesV2){
    const m=state.machines.find(x=>String(x.number).trim()==='37');
    if(m){
      const drinkNames=new Set(['v no suger','v no sugar','coke no suger','coke no sugar','solo','v','passiona','gaterade','gatorade','mother','ice coffee','iced coffee','ribena','redbull','red bull','blue v','iced tea']);
      const chipNames=new Set(['doritos','original','chicken','cheese & onion','salt & vinegar','bbq','burger ring','burger rings','chilli kettle','noodle c & b']);
      m.products.forEach(p=>{
        const n=String(p.name||'').trim().toLowerCase().replace(/\s+/g,' ');
        if(drinkNames.has(n)) p.category='Drinks';
        else if(chipNames.has(n)) p.category='Chips';
        else p.category='Chocolate';
      });
    }
    state.migrations.holdmark37CategoriesV2=true;
    save();
  }
  if(!state.migrations.safetyLockerSalesV1){
    Object.entries(SAFETY_LOCKERS).forEach(([number,items])=>{
      const m=state.machines.find(x=>String(x.number).trim()===number);
      if(!m)return;
      m.safetySales=items.map(item=>({...item}));
      const lockerProductIds=new Set(items.map(item=>item.productId));
      (m.products||[]).forEach(product=>{
        if(lockerProductIds.has(product.id))product.category='Locker';
      });
    });
    state.migrations.safetyLockerSalesV1=true;
    save();
  }
  if(!state.migrations.safetyLockerPhotosV1){
    Object.entries(SAFETY_LOCKER_PHOTOS).forEach(([number,photo])=>{
      const m=state.machines.find(x=>String(x.number).trim()===number);
      if(m&&!m.safetyPhoto)m.safetyPhoto=photo;
    });
    state.migrations.safetyLockerPhotosV1=true;
    save();
  }
  if(!state.migrations.machine59MainPhotoV2){
    const m=state.machines.find(x=>String(x.number).trim()==='59');
    if(m)m.photo='machine-59-main.jpg';
    state.migrations.machine59MainPhotoV2=true;
    save();
  }
}
function cleanup(){let cut=new Date();cut.setMonth(cut.getMonth()-6);let iso=cut.toISOString();state.machines.forEach(m=>{m.fills=(m.fills||[]).filter(f=>f.date>=iso);recalcLast(m)});state.runs=(state.runs||[]).filter(r=>r.date>=iso.slice(0,10));save()}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function machineById(id){return state.machines.find(m=>String(m.id)===String(id))}
function recalcLast(m){m.lastFill=(m.fills||[]).length?[...m.fills].sort((a,b)=>b.date.localeCompare(a.date))[0].date:null}
function daysSince(date){if(!date)return null;return Math.max(0,Math.floor((new Date()-new Date(date))/86400000))}
function status(m){let d=daysSince(m.lastFill);return d===null?['grey','Never filled']:d<=2?['green',`${d} day${d===1?'':'s'}`]:d<=6?['orange',`${d} days`]:['red',`${d} days`]}
function fmtDate(s,withTime=false){if(!s)return 'Never';let d=new Date(s);return d.toLocaleString('en-AU',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'})}
function nav(){return `<nav class="bottom-nav">${[['dashboard','⌂','Dashboard'],['run','✓','Run'],['machines','⌕','Machines'],['settings','⚙','Settings']].map(x=>`<button class="nav-btn ${page===x[0]?'active':''}" data-page="${x[0]}"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</nav>`}
function shell(title,body,extra=''){return `<header><div class="brand">VENDINGFORYOU NSW</div><div class="header-row"><h1>${title}</h1><span class="sync-pill">● Local</span></div></header><main class="main">${body}</main>${extra}${nav()}`}
function render(){selectedMachine&&page==='machine'?renderMachine():page==='dashboard'?renderDashboard():page==='run'?renderRun():page==='machines'?renderMachines():renderSettings();bindCommon()}
function bindCommon(){$$('.nav-btn').forEach(b=>b.onclick=()=>{page=b.dataset.page;selectedMachine=null;render()})}
function renderDashboard(){let active=state.machines.filter(m=>m.active!==false), red=active.filter(m=>status(m)[0]==='red').length, run=getRun(today()), done=run?run.jobs.filter(j=>j.done).length:0;let recent=[...active].sort((a,b)=>(b.lastFill||'').localeCompare(a.lastFill||'')).slice(0,8);$('#app').innerHTML=shell('Dashboard',`<div class="grid"><div class="card metric"><strong>${active.length}</strong><span>Active machines</span></div><div class="card metric"><strong>${run?.jobs.length||0}</strong><span>Jobs today</span></div><div class="card metric"><strong>${done}</strong><span>Done today</span></div><div class="card metric"><strong class="danger-text">${red}</strong><span>7+ days</span></div></div><div class="section-title"><h2>Recently filled</h2></div><div class="list">${recent.map(machineCard).join('')||empty('No machines')}</div>`);bindMachineCards()}
function machineCard(m){let [c,t]=status(m);return `<div class="machine-card" data-mid="${m.id}"><div class="number">#${esc(m.number)}</div><div class="grow"><div class="title">${esc(m.site||'Unnamed site')}</div><div class="sub">${esc(m.suburb||m.address||'No location')}</div></div><span class="dot ${c}"></span><span class="muted">${t}</span></div>`}
function bindMachineCards(){$$('[data-mid]').forEach(e=>e.onclick=()=>{selectedMachine=e.dataset.mid;page='machine';machineTab='details';render()})}
function renderMachines(){let active=state.machines.filter(m=>m.active!==false).sort((a,b)=>Number(a.number)-Number(b.number));$('#app').innerHTML=shell('Machines',`<input class="search" id="machineSearch" placeholder="Search number, site or suburb"><div class="section-title"><h2>${active.length} active</h2><button class="btn small" id="addMachine">+ Add</button></div><div class="list" id="machineList">${active.map(machineCard).join('')}</div>`);bindMachineCards();$('#machineSearch').oninput=e=>{let q=e.target.value.toLowerCase();$('#machineList').innerHTML=active.filter(m=>[m.number,m.site,m.suburb,m.address].join(' ').toLowerCase().includes(q)).map(machineCard).join('')||empty('No matches');bindMachineCards()};$('#addMachine').onclick=()=>editMachineModal()}
function renderMachine(){let m=machineById(selectedMachine);if(!m){page='machines';return render()}let [c,t]=status(m);let tabs=[['details','Details'],['fill','New Fill'],...(m.safetySales?.length?[['safety','Safety Sales']]:[]),['history','History'],['products','Products']];let content=machineTab==='details'?detailsTab(m):machineTab==='fill'?fillTab(m):machineTab==='safety'?safetySalesTab(m):machineTab==='history'?historyTab(m):productsTab(m);$('#app').innerHTML=`<header><div class="header-row"><button class="back" id="backBtn">←</button><div class="grow"><div class="brand">MACHINE #${esc(m.number)}</div><h1>${esc(m.site||'Unnamed')}</h1></div><span class="dot ${c}"></span></div></header><main class="main"><div class="tabs">${tabs.map(x=>`<button class="tab ${x[0]==='safety'?'safety-tab':''} ${machineTab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div>${content}</main>${nav()}`;$('#backBtn').onclick=()=>{page='machines';selectedMachine=null;render()};$$('[data-tab]').forEach(b=>b.onclick=()=>{machineTab=b.dataset.tab;render()});bindCommon();bindMachineTab(m)}
function detailsTab(m){return `${m.photo?`<img class="detail-photo" id="machinePhoto" src="${esc(m.photo)}" alt="Machine #${esc(m.number)}" onerror="this.style.display='none'">`:''}<div class="detail-grid" style="margin-top:12px">${[['Last fill',fmtDate(m.lastFill,true)],['Address',m.address||'—'],['Suburb',m.suburb||'—'],['Contact',m.contact||'—'],['Phone',m.phone||'—'],['Serial',m.serial||'—']].map(x=>`<div class="detail-item"><label>${x[0]}</label><div>${esc(x[1])}</div></div>`).join('')}</div><div class="card" style="margin-top:12px"><b>Notes</b><p class="muted">${esc(m.notes||'No notes')}</p></div><div class="actions"><button class="btn" id="editMachine">Edit machine</button><button class="btn secondary" id="changePhoto">Change photo</button></div><input type="file" accept="image/*" capture="environment" id="photoInput" hidden>`}
function fillTab(m){let groups=[['Chocolate','Chocolate'],['Drinks','Drinks'],['Chips','Chips'],['Locker','Safety Locker Stock']];return `<div class="field"><label>Fill date and time</label><input id="fillDate" type="datetime-local" value="${new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}"></div>${groups.map(([g,label])=>{let ps=m.products.filter(p=>p.category===g);return ps.length?`<div class="section-title"><h2>${label}</h2></div><div class="list">${ps.map(p=>`<div class="product-row"><div><div class="title">${esc(p.name)}</div><div class="sub">Full: ${esc(p.par??'—')}</div></div><input inputmode="numeric" min="0" type="number" placeholder="Qty" data-qty="${p.id}">${p.boxEnabled?`<input inputmode="numeric" min="0" type="number" placeholder="Boxes" data-box="${p.id}">`:'<span></span>'}</div>`).join('')}</div>`:''}).join('')}<div class="actions"><button class="btn" id="saveFill">Save Fill</button><button class="btn secondary" id="doneNoFill">Mark job done only</button></div>`}
function safetySalesTab(m){let items=m.safetySales||[],totalItems=items.reduce((sum,item)=>sum+Number(item.sold||0),0),salesValue=items.reduce((sum,item)=>sum+Number(item.sold||0)*Number(item.price||0),0);return `<div class="safety-photo-card">${m.safetyPhoto?`<img class="safety-photo" id="safetyPhoto" src="${esc(m.safetyPhoto)}" alt="Safety locker for machine #${esc(m.number)}" onerror="this.closest('.safety-photo-card').classList.add('photo-missing');this.style.display='none'">`:`<div class="safety-photo-empty"><strong>No locker photo in workbook</strong><span>Add one from this device or take a new photo.</span></div>`}<button class="btn safety-photo-btn" id="changeSafetyPhoto">${m.safetyPhoto?'Change locker photo':'Add locker photo'}</button><input type="file" accept="image/*" capture="environment" id="safetyPhotoInput" hidden></div><div class="safety-summary"><div class="card metric"><strong>${totalItems}</strong><span>All-time items sold</span></div><div class="card metric"><strong>${salesValue.toLocaleString('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0})}</strong><span>All-time sales value</span></div></div><div class="section-title"><div><h2>Safety equipment sold</h2><div class="sub safety-help">Tap + each time one sells. Use − to correct a mistake.</div></div></div><div class="safety-sales-list">${items.map(item=>`<div class="safety-sale-row"><div class="safety-item"><div class="title">${esc(item.name)}</div><div class="sub">$${Number(item.price||0).toFixed(0)} each</div></div><div class="safety-counter"><button class="counter-btn minus" data-safety-change="-1" data-safety-id="${esc(item.id)}" aria-label="Remove one ${esc(item.name)} sale">−</button><strong>${Number(item.sold||0)}</strong><button class="counter-btn plus" data-safety-change="1" data-safety-id="${esc(item.id)}" aria-label="Add one ${esc(item.name)} sale">+</button></div></div>`).join('')}</div><p class="persistent-note">These are permanent all-time totals and are not removed with six-month fill history.</p>`}
function historyTab(m){let fills=[...(m.fills||[])].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="section-title"><h2>${fills.length} fills</h2></div><div class="list">${fills.map(f=>{let entries=f.entries.filter(e=>e.quantity||e.boxes);return `<div class="history-card" data-fid="${f.id}"><div class="grow"><div class="title">${fmtDate(f.date,true)}</div><div class="sub">${entries.map(e=>{let p=m.products.find(x=>x.id===e.productId);return `${p?.name||'Removed product'} ${e.quantity||''}${e.boxes?` + ${e.boxes} box${e.boxes===1?'':'es'}`:''}`}).join(' • ')||'No items recorded'}</div></div><button class="btn small secondary" data-editfill="${f.id}">Edit</button></div>`}).join('')||empty('No fill history')}</div>`}
function productsTab(m){let groups=['Chocolate','Drinks','Chips','Locker'];return `<div class="section-title"><div><h2>${m.products.length} products</h2><div class="sub">Hold and drag a product, or tap Move.</div></div><button class="btn small" id="addProduct">+ Add</button></div><div class="category-board">${groups.map(g=>{let ps=m.products.filter(p=>p.category===g);return `<section class="category-zone" data-category="${g}"><div class="category-heading"><h3>${g}</h3><span>${ps.length}</span></div><div class="category-products">${ps.map(p=>`<div class="product-card-draggable" draggable="true" data-product-id="${p.id}"><div class="drag-handle">⋮⋮</div><div class="grow"><div class="title">${esc(p.name)}</div><div class="sub">Full ${esc(p.par)} ${p.boxEnabled?'• Boxes':''}</div></div><button class="btn small secondary" data-moveproduct="${p.id}">Move</button><button class="btn small secondary" data-editproduct="${p.id}">Edit</button></div>`).join('')||'<div class="category-empty">Drop products here</div>'}</div></section>`}).join('')}</div>`}
function bindMachineTab(m){if(machineTab==='details'){$('#editMachine').onclick=()=>editMachineModal(m);$('#changePhoto').onclick=()=>$('#photoInput').click();let photo=$('#machinePhoto');if(photo){photo.setAttribute('role','button');photo.setAttribute('tabindex','0');const show=()=>openPhotoViewer(photo.currentSrc||photo.src,m);photo.addEventListener('click',show);photo.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}});}$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{m.photo=r.result;save();render();toast('Photo saved')};r.readAsDataURL(f)}}if(machineTab==='fill'){$('#saveFill').onclick=()=>saveFill(m);$('#doneNoFill').onclick=()=>{markJobDone(m.id,$('#fillDate').value);toast('Marked done');page='run';render()}}if(machineTab==='safety'){let safetyPhoto=$('#safetyPhoto');if(safetyPhoto){safetyPhoto.setAttribute('role','button');safetyPhoto.setAttribute('tabindex','0');const show=()=>openPhotoViewer(safetyPhoto.currentSrc||safetyPhoto.src,m);safetyPhoto.addEventListener('click',show);safetyPhoto.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}})}$('#changeSafetyPhoto').onclick=()=>$('#safetyPhotoInput').click();$('#safetyPhotoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{m.safetyPhoto=r.result;save();render();toast('Locker photo saved')};r.readAsDataURL(f)};$$('[data-safety-change]').forEach(button=>button.onclick=()=>{let item=(m.safetySales||[]).find(x=>x.id===button.dataset.safetyId);if(!item)return;let next=Number(item.sold||0)+Number(button.dataset.safetyChange);if(next<0)return toast('Sold total cannot go below 0');item.sold=next;save();render();toast(`${item.name}: ${item.sold} sold`)})}if(machineTab==='history'){$$('[data-editfill]').forEach(b=>b.onclick=e=>{e.stopPropagation();editFillModal(m,b.dataset.editfill)})}if(machineTab==='products'){$('#addProduct').onclick=()=>editProductModal(m);$$('[data-editproduct]').forEach(b=>b.onclick=()=>editProductModal(m,m.products.find(p=>p.id===b.dataset.editproduct)));$$('[data-moveproduct]').forEach(b=>b.onclick=e=>{e.stopPropagation();moveProductModal(m,b.dataset.moveproduct)});bindProductDrag(m)}}
function openPhotoViewer(src,m){let b=document.createElement('div');b.className='photo-viewer';b.innerHTML=`<button class="photo-close" aria-label="Close photo">×</button><img src="${esc(src)}" alt="Machine #${esc(m.number)} full photo">`;document.body.appendChild(b);let close=()=>b.remove();b.onclick=e=>{if(e.target===b||e.target.closest('.photo-close'))close()};document.addEventListener('keydown',function k(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',k)}})}
function moveProductModal(m,pid){let p=m.products.find(x=>x.id===pid);if(!p)return;let groups=['Chocolate','Drinks','Chips','Locker'];let b=modal(`<h2>Move ${esc(p.name)}</h2><div class="field"><label>Category</label><select id="moveCategory">${groups.map(g=>`<option ${p.category===g?'selected':''}>${g}</option>`).join('')}</select></div><div class="actions"><button class="btn" id="confirmMove">Move product</button><button class="btn secondary" id="cancel">Cancel</button></div>`);$('#cancel',b).onclick=()=>b.remove();$('#confirmMove',b).onclick=()=>{p.category=$('#moveCategory',b).value;save();b.remove();render();toast('Product moved')}}
function bindProductDrag(m){let dragged=null;$$('.product-card-draggable').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card.dataset.productId;card.classList.add('dragging')});card.addEventListener('dragend',()=>{card.classList.remove('dragging');$$('.category-zone').forEach(z=>z.classList.remove('drag-over'))})});$$('.category-zone').forEach(zone=>{zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('drag-over')});zone.addEventListener('dragleave',e=>{if(!zone.contains(e.relatedTarget))zone.classList.remove('drag-over')});zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('drag-over');let p=m.products.find(x=>x.id===dragged);if(p&&p.category!==zone.dataset.category){p.category=zone.dataset.category;save();render();toast('Product moved')}})})}
function saveFill(m){let entries=m.products.map(p=>({productId:p.id,quantity:Number($(`[data-qty="${p.id}"]`)?.value||0),boxes:Number($(`[data-box="${p.id}"]`)?.value||0)})).filter(e=>e.quantity||e.boxes);if(!entries.length&&!confirm('Save an empty fill record?'))return;let date=new Date($('#fillDate').value).toISOString();m.fills=m.fills||[];m.fills.push({id:uid('fill'),date,entries,source:'app'});recalcLast(m);markJobDone(m.id,date);save();toast('Fill saved');machineTab='history';render()}
function getRun(date){return (state.runs||[]).find(r=>r.date===date)} function ensureRun(date){let r=getRun(date);if(!r){r={id:uid('run'),date,jobs:[],source:'app'};(state.runs||=[]).push(r)}return r}
function markJobDone(mid,date){let r=getRun((date||today()).slice(0,10));if(!r)return;let j=r.jobs.find(j=>String(j.machineId)===String(mid));if(j){j.done=true;j.doneAt=new Date(date||Date.now()).toISOString();save()}}
function renderRun(){let r=getRun(runDate), jobs=r?.jobs||[];$('#app').innerHTML=shell('Daily Run',`<div class="field"><label>Run date</label><input id="runDate" type="date" value="${runDate}"></div><div class="section-title"><h2>${jobs.filter(j=>j.done).length}/${jobs.length} done</h2><button class="btn small" id="addRunJob">+ Add machine</button></div><div class="list">${jobs.map((j,i)=>{let m=machineById(j.machineId);return `<div class="job-card ${j.done?'done':''}" data-job="${i}"><div class="checkbox">${j.done?'✓':''}</div><div class="grow"><div class="title">#${esc(m?.number||'?')} — ${esc(m?.site||'Missing machine')}</div><div class="sub">${esc(m?.suburb||m?.address||'')}${j.doneAt?' • '+fmtDate(j.doneAt,true):''}</div></div><button class="btn small danger" data-removejob="${i}">Remove</button></div>`}).join('')||empty('No machines added for this date')}</div>`);$('#runDate').onchange=e=>{runDate=e.target.value;render()};$('#addRunJob').onclick=()=>addRunJobModal();$$('[data-job]').forEach(e=>e.onclick=ev=>{if(ev.target.closest('[data-removejob]'))return;let j=jobs[Number(e.dataset.job)];j.done=!j.done;j.doneAt=j.done?new Date().toISOString():null;save();render()});$$('[data-removejob]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(confirm('Remove this machine from the run?')){jobs.splice(Number(b.dataset.removejob),1);save();render()}})}
function renderSettings(){let last=state.updatedAt?fmtDate(state.updatedAt,true):'—';$('#app').innerHTML=shell('Settings',`<div class="card"><h2>Data</h2><p class="muted">All changes are saved on this device. Logs older than six months are automatically removed.</p><div class="detail-item"><label>Last saved</label>${last}</div><div class="actions"><button class="btn" id="exportData">Export backup</button><button class="btn secondary" id="importData">Import backup</button></div><input type="file" accept="application/json" id="importFile" hidden></div><div class="card" style="margin-top:12px"><h2>Cloud sync</h2><p class="muted">This static GitHub version is local-only. Shared multi-device syncing needs a private cloud database connected once.</p><span class="badge">Not connected</span></div><div class="card" style="margin-top:12px"><h2>Archived machines</h2><p class="muted">${state.machines.filter(m=>m.active===false).length} archived</p><button class="btn secondary" id="showArchived">Manage archived</button></div><div class="actions"><button class="btn danger" id="resetApp">Reset to workbook data</button></div>`);$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importFile').click();$('#importFile').onchange=importData;$('#resetApp').onclick=async()=>{if(confirm('Delete local changes and restore the original workbook import?')){localStorage.removeItem(APP_KEY);location.reload()}};$('#showArchived').onclick=archivedModal}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function modal(html){let b=document.createElement('div');b.className='modal-backdrop';b.innerHTML=`<div class="modal">${html}</div>`;b.onclick=e=>{if(e.target===b)b.remove()};document.body.appendChild(b);return b}
function editMachineModal(m=null){let isNew=!m;m=m||{id:uid('machine'),number:'',site:'',suburb:'',address:'',contact:'',phone:'',serial:'',notes:'',active:true,products:[],fills:[],lastFill:null};let b=modal(`<h2>${isNew?'Add':'Edit'} machine</h2>${[['number','Machine number'],['site','Site/company'],['suburb','Suburb'],['address','Address'],['contact','Contact'],['phone','Phone'],['serial','Serial number']].map(x=>`<div class="field"><label>${x[1]}</label><input id="f_${x[0]}" value="${esc(m[x[0]]||'')}"></div>`).join('')}<div class="field"><label>Notes</label><textarea id="f_notes">${esc(m.notes||'')}</textarea></div><div class="actions"><button class="btn" id="saveMachine">Save</button>${!isNew?`<button class="btn danger" id="archiveMachine">${m.active===false?'Restore':'Archive'}</button>`:''}<button class="btn secondary" id="cancel">Cancel</button></div>`);$('#cancel',b).onclick=()=>b.remove();$('#saveMachine',b).onclick=()=>{let num=$('#f_number',b).value.trim();if(!num)return toast('Machine number required');if(isNew&&state.machines.some(x=>String(x.number)===num))return toast('That machine number already exists');['number','site','suburb','address','contact','phone','serial','notes'].forEach(k=>m[k]=$('#f_'+k,b).value.trim());if(isNew)state.machines.push(m);save();b.remove();selectedMachine=m.id;page='machine';render();toast('Machine saved')};if(!isNew)$('#archiveMachine',b).onclick=()=>{m.active=m.active===false;save();b.remove();page='machines';selectedMachine=null;render();toast(m.active?'Machine restored':'Machine archived')}}
function editProductModal(m,p=null){let isNew=!p;p=p||{id:uid(m.id+'-product'),name:'',category:'Chocolate',par:0,boxEnabled:false};let b=modal(`<h2>${isNew?'Add':'Edit'} product</h2><div class="field"><label>Name</label><input id="p_name" value="${esc(p.name)}"></div><div class="field"><label>Category</label><select id="p_cat">${['Chocolate','Drinks','Chips','Locker'].map(c=>`<option ${p.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Full/par amount</label><input type="number" min="0" id="p_par" value="${esc(p.par)}"></div><div class="field"><label><input type="checkbox" id="p_box" ${p.boxEnabled?'checked':''}> Allow box entry</label></div><div class="actions"><button class="btn" id="saveProduct">Save</button>${!isNew?'<button class="btn danger" id="deleteProduct">Delete</button>':''}<button class="btn secondary" id="cancel">Cancel</button></div>`);$('#cancel',b).onclick=()=>b.remove();$('#saveProduct',b).onclick=()=>{p.name=$('#p_name',b).value.trim();if(!p.name)return toast('Product name required');p.category=$('#p_cat',b).value;p.par=Number($('#p_par',b).value||0);p.boxEnabled=$('#p_box',b).checked;if(isNew)m.products.push(p);save();b.remove();render();toast('Product saved')};if(!isNew)$('#deleteProduct',b).onclick=()=>{if(confirm('Delete this product? Old history will keep the product ID only.')){m.products=m.products.filter(x=>x.id!==p.id);save();b.remove();render()}}}
function editFillModal(m,fid){let f=m.fills.find(x=>x.id===fid);let b=modal(`<h2>Edit fill</h2><div class="field"><label>Date and time</label><input type="datetime-local" id="ef_date" value="${new Date(new Date(f.date)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}"></div><div class="list">${m.products.map(p=>{let e=f.entries.find(x=>x.productId===p.id)||{};return `<div class="product-row"><div class="title">${esc(p.name)}</div><input type="number" min="0" data-efq="${p.id}" value="${e.quantity||''}" placeholder="Qty">${p.boxEnabled?`<input type="number" min="0" data-efb="${p.id}" value="${e.boxes||''}" placeholder="Boxes">`:'<span></span>'}</div>`}).join('')}</div><div class="actions"><button class="btn" id="saveEditFill">Save</button><button class="btn danger" id="deleteFill">Delete</button><button class="btn secondary" id="cancel">Cancel</button></div>`);$('#cancel',b).onclick=()=>b.remove();$('#saveEditFill',b).onclick=()=>{f.date=new Date($('#ef_date',b).value).toISOString();f.entries=m.products.map(p=>({productId:p.id,quantity:Number($(`[data-efq="${p.id}"]`,b)?.value||0),boxes:Number($(`[data-efb="${p.id}"]`,b)?.value||0)}));recalcLast(m);save();b.remove();render();toast('Fill updated')};$('#deleteFill',b).onclick=()=>{if(confirm('Delete this fill permanently?')){m.fills=m.fills.filter(x=>x.id!==fid);recalcLast(m);save();b.remove();render();toast('Fill deleted')}}}
function addRunJobModal(){let active=state.machines.filter(m=>m.active!==false).sort((a,b)=>Number(a.number)-Number(b.number));let b=modal(`<h2>Add machine to ${fmtDate(runDate)}</h2><input class="search" id="jobSearch" placeholder="Search machine"><div class="list" id="jobResults" style="margin-top:12px">${active.map(machineCard).join('')}</div><div class="actions"><button class="btn secondary" id="cancel">Cancel</button></div>`);function bind(){$$('[data-mid]',b).forEach(e=>e.onclick=()=>{let r=ensureRun(runDate);if(r.jobs.some(j=>String(j.machineId)===e.dataset.mid))return toast('Already on this run');r.jobs.push({machineId:e.dataset.mid,done:false,doneAt:null});save();b.remove();render();toast('Machine added')})}bind();$('#jobSearch',b).oninput=e=>{let q=e.target.value.toLowerCase();$('#jobResults',b).innerHTML=active.filter(m=>[m.number,m.site,m.suburb].join(' ').toLowerCase().includes(q)).map(machineCard).join('');bind()};$('#cancel',b).onclick=()=>b.remove()}
function archivedModal(){let ar=state.machines.filter(m=>m.active===false);let b=modal(`<h2>Archived machines</h2><div class="list">${ar.map(machineCard).join('')||empty('None archived')}</div><div class="actions"><button class="btn secondary" id="cancel">Close</button></div>`);$$('[data-mid]',b).forEach(e=>e.onclick=()=>{let m=machineById(e.dataset.mid);m.active=true;save();b.remove();render();toast('Machine restored')});$('#cancel',b).onclick=()=>b.remove()}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`VFY-NSW-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.machines))throw 0;if(confirm('Replace this device data with the selected backup?')){state=d;migrateState();cleanup();save();render();toast('Backup imported')}}catch{alert('That file is not a valid VendingForYou backup')}};r.readAsText(f)}
init().catch(e=>{$('#app').innerHTML=`<div class="empty"><h2>Could not load app data</h2><p>${esc(e.message)}</p></div>`});
